---@meta _
-- Generated API for game version 0.9.1

---@class HttpFileRouter : RefCounted
---@field localpath string
---@field index_page string
---@field fallback_page string
---@field extensions PackedStringArray
---@field exclude_extensions PackedStringArray
---@field listfiles boolean
---@field weekdays Array<string>
---@field monthnames Array<string>
---@field path string
---@field rpath RegEx
---@field params Array<string>
---@field handle_get (Callable|function)
---@field handle_post (Callable|function)
---@field handle_head (Callable|function)
---@field handle_put (Callable|function)
---@field handle_patch (Callable|function)
---@field handle_delete (Callable|function)
---@field handle_options (Callable|function)
---@field condition (Callable|function)
local HttpFileRouter = {}
